apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 4.1.1
    helm:
      releaseName: falco
      parameters:
        - name: driver.kind
          value: "ebpf"
        - name: tty
          value: "true"
        - name: falcosidekick.enabled
          value: "true"
        - name: falcosidekick.config.syslog.host
          value: "your.syslog.server.ip"
        - name: falcosidekick.config.syslog.port
          value: "514"
        - name: falcosidekick.config.syslog.protocol
          value: "tcp" # or "udp"
        - name: falcosidekick.config.customfields
          value: "user:lewie"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: falco
  syncPolicy:
    automated:
      prune: true # Enables automatic pruning of resources
      selfHeal: true # Enables auto-healing of resources
    syncOptions:
      - CreateNamespace=true # Allows Argo CD to create the namespace if it doesn't exist
